# Generated by Django 3.2.16 on 2022-11-19 15:44

from django.db import migrations, models
import lingomeets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(blank=True, validators=[lingomeets.validators.validate_textfields]),
        ),
    ]
