# Generated by Django 3.2.16 on 2022-11-22 17:06

import django.core.validators
from django.db import migrations, models
import lingomeets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, validators=[lingomeets.validators.validate_textfields]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native_language',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical letters allowed.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_language',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical letters allowed.')]),
        ),
    ]
