# Generated by Django 3.2.16 on 2022-11-26 10:33

import django.core.validators
from django.db import migrations, models
import lingomeets.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20221122_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, validators=[lingomeets.validators.validate_birthday]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('[^0-9]+')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('[^0-9]+')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='native_language',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator('[^0-9]+')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='other_language',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator('[^0-9]+')]),
        ),
    ]
